language: node_js
node_js:
  - 6
  - 8
  - node
cache:
  yarn: true
  directories:
    - node_modules
env:
  matrix:
    - JOB=test
matrix:
  fast_finish: true
  include:
    - node_js: node
      env: JOB=lint
before_script:
  - |
    if [ "${JOB}" = "test" ] && [ -n "$(git diff)" ]; then
      echo "Generated is out of sync"
      exit 1
    fi
script:
  - yarn $JOB
