language: node_js
node_js:
  - node
  - 8
  - 6
cache:
  yarn: true
  directories:
    - node_modules
env:
  matrix:
    - JOB=test
matrix:
  fast_finish: true
  include:
    - env: JOB=check-diff
    - env: JOB=lint
script:
  - make $JOB
